import enum
from datetime import datetime, timezone
from typing import List, Dict, Any
from schema import Schema, And, Or, Use, SchemaError
from models.base import BaseModel

class StepType(enum.IntEnum):
    NOP = 0                 # No operation, pass the signal through unchanged
    DC_SPIKE = 1            # Remove DC spikes from the signal
    LOAD = 2                # Apply load to the signal
    GAIN_CAL = 3            # Perform gain calibration
    TSYS_CAL = 4            # Perform system temperature calibration
    RFI_FLAG = 5            # Flag radio frequency interference
    QA = 6                  # Calculate signal quality attributes (SNR, signal power, noise power, etc.)
    # Add more step types as needed

class StepConfig(BaseModel):
    """A class representing the configuration for a single processing step in the signal processing pipeline."""

    schema = Schema({
        "_type": And(str, lambda v: v == "StepConfig"),
        "step": Or(StepType, And(str, lambda v: isinstance(v, str))),     # Built-in StepType or custom registry key / class path
        "params": And(dict, lambda v: isinstance(v, dict)),               # Parameters for the processing step
        "last_update": And(datetime, lambda v: isinstance(v, datetime)),  # Timestamp when the step config was last updated
    })

    allowed_transitions = {}

    def __init__(self, **kwargs):

        # Default values
        defaults = {
            "_type": "StepConfig",
            "step": StepType.NOP,
            "params": {"pipeline": "cal"},              # Default to "cal" pipeline as opposed to "SPR" pipeline
            "last_update": datetime.now(timezone.utc)
        }

        # Apply defaults if not provided in kwargs
        for key, value in defaults.items():
            if key not in kwargs:
                kwargs.setdefault(key, value)

        super().__init__(**kwargs)

    def get_step_key(self) -> str:
        if isinstance(self.step, StepType):
            return self.step.name.lower()
        return str(self.step).strip().lower()

    def __str__(self):
        step_name = self.step.name if isinstance(self.step, StepType) else str(self.step)
        return f"StepConfig(step={step_name}, params={self.params}, last_update={self.last_update.isoformat()})"

    # Make sure there are no object references in the params when serialising steps e.g. into JSON for transmission to Telescope Manager
    # in status updates. Object references are inserted into params for Pipeline processing in order to provide context
    def to_dict(self):
        # Filter params to only include serializable types
        serializable_params = {k: v for k, v in self.params.items() if isinstance(v, (str, int, float, bool, list, dict, type(None)))}
        # Temporarily replace self.params with the filtered version
        original_params = self.params
        self.params = serializable_params
        result = super().to_dict()
        self.params = original_params  # Restore original params
        return result

class PipelineConfig(BaseModel):
    """
    Configuration for pipelines generated by the pipeline factory
    Supports per-digitiser and default sets of steps.
    steps_map: dict mapping dig_id or 'default' to list of StepConfig

    Example usage:
    steps_map = {
        "default": [StepConfig(step=StepType.REMOVE_DC_SPIKE, params={}), StepConfig(step=StepType.APPLY_LOAD, params={})],
        "dig001": [StepConfig(step=StepType.REMOVE_DC_SPIKE, params={}), StepConfig(step=StepType.RFI_FLAGGING, params={"threshold": 5.0})],
    }   
    """
    schema = Schema({
        "_type": And(str, lambda v: v == "PipelineConfig"),
        "steps_map": And(dict, lambda v: all(isinstance(k, str) and isinstance(val, list) and all(isinstance(item, StepConfig) for item in val) for k, val in v.items())),
        "last_update": And(datetime, lambda v: isinstance(v, datetime)),
    })

    def __init__(self, **kwargs):

        step1 = StepConfig(step=StepType.LOAD, params={})
        default_steps={"default": [step1]}

        defaults = {
            "_type": "PipelineConfig",
            "steps_map": default_steps,
            "last_update": datetime.now(timezone.utc)
        }
        for key, value in defaults.items():
            if key not in kwargs:
                kwargs.setdefault(key, value)
        super().__init__(**kwargs)

    def __str__(self):

        str_repr = f"PipelineConfig(last_update={self.last_update.isoformat()}, steps_map=({len(self.steps_map)} items))\n"
        for dig_id, steps in self.steps_map.items():
            str_repr += f"  '{dig_id}': [\n"
            for step in steps:
                str_repr += f"    {step},\n"
            str_repr += "  ],\n"
        str_repr += "})"
        return str_repr

    def get_steps(self, dig_id):
        return self.steps_map.get(dig_id, self.steps_map.get("default", []))

if __name__ == "__main__":
    import pprint
    step1 = StepConfig(step=StepType.DC_SPIKE, params={"context": "spr"})
    step2 = StepConfig(step=StepType.LOAD, params={"context": "cal"})
    step3 = StepConfig(step=StepType.RFI_FLAG, params={"context": "cal", "threshold": 5, "window_size": 21})
    step4 = StepConfig(step=StepType.QA, params={"context": "cal", "window_frac": 0.2})
    config = PipelineConfig(steps_map={
        "default": [step1, step2, step3, step4],
        "dig001": [step1, step4],
    })
    print("="*40)
    print(config)
    print("="*40)

    dig001_steps = config.get_steps("dig001")
    print("Steps for dig001:")
    for step in dig001_steps:
        print(step)

    dig002_steps = config.get_steps("dig002")
    print("\nSteps for dig002 (should use default):")
    for step in dig002_steps:
        print(step)

    config.save_to_disk()